using Test

@testset "EMMoMSuite" begin
    include("test_materials.jl")
    include("test_geometry.jl")
    include("test_basis_functions.jl")
    include("test_integral_equations.jl")
    include("test_fastexp.jl")
    include("test_mfie_decomposition.jl")
    include("test_mfie_near_quadrature.jl")
    include("test_solvers.jl")
    include("test_solvers_verification.jl")
    include("test_preconditioners.jl")
    include("test_mlfma.jl")
    include("test_mlfma_params.jl")
    include("test_aca.jl")
    include("test_block_evaluator.jl")
    include("test_block_evaluator_pmchw.jl")
    include("test_aca_operator.jl")
    include("test_mlaca_operator.jl")
    include("test_lowfreq_aca.jl")
    include("test_parallel.jl")
    include("test_mpiarray.jl")
    include("test_parallel_mfie_cfie.jl")
    include("test_distributed_gmres.jl")
    include("test_volume_assembly_mpi.jl")
    include("test_mpi_array_utils.jl")
    include("test_lebedev.jl")
    include("test_lebedev_interp.jl")
    include("test_postprocessing.jl")
    include("test_antenna_feeds.jl")
    include("test_io.jl")
    include("test_integration.jl")
    include("test_workflow.jl")
    include("test_scfie.jl")
    include("test_pwc.jl")
    include("test_hex_rbf.jl")
    include("test_pmchw_excitation.jl")
    include("test_scfie_delta_gap.jl")
    include("test_pmchw.jl")
    include("test_nmuller.jl")
    include("test_nmuller_excitation.jl")
    include("test_nmuller_comparison.jl")
    include("test_pmchw_operator_shell.jl")
    include("test_pmchw_operator_shell_mlfma.jl")
    include("test_pmchw_gate_s_dense.jl")
    include("test_ports.jl")
    include("test_postprocessing_advanced.jl")
    include("test_feko_reader.jl")
    include("test_accuracy_metrics.jl")
    include("test_benchmark_report_data.jl")
    include("test_release_workflow.jl")
    include("test_legacy_parity.jl")
    
    # Phase 21: Coverage gap tests for Round 6-12 fixes
    include("test_coverage_gaps.jl")
    
    # Phase 21.2: Integration tests (end-to-end solves)
    include("test_integral_equations_endtoend.jl")
    
    # Phase 21.3: Numerical validation (frequency sweeps)
    include("test_integral_equations_frequency.jl")
end
