using Test

@testset "EMSuite" begin
    include("test_materials.jl")
    include("test_geometry.jl")
    include("test_basis_functions.jl")
    include("test_integral_equations.jl")
    include("test_fastexp.jl")
    include("test_mfie_decomposition.jl")
    include("test_solvers.jl")
    include("test_solvers_verification.jl")
    include("test_preconditioners.jl")
    include("test_mlfma.jl")
    include("test_parallel.jl")
    include("test_mpiarray.jl")
    include("test_parallel_mfie_cfie.jl")
    include("test_distributed_gmres.jl")
    include("test_volume_assembly_mpi.jl")
    include("test_lebedev.jl")
    include("test_postprocessing.jl")
    include("test_io.jl")
    include("test_integration.jl")
    include("test_workflow.jl")
    include("test_scfie.jl")
    include("test_pwc.jl")
end
