name = "G8_torus_EFIE"
geo = "torus.geo"
mesh_size = 0.05
dim = 2
freq = 1.2e9
ie = "EFIE"
alpha = 0.5
theta_inc = 1.5707963267948966
phi_inc = 3.141592653589793
pol = [0.0, 0.0, 1.0]
n_theta = 181
phi_cuts = [0.0, 1.5707963267948966]

[[interface]]
surface = "body"
plus = "dielectric:1:0:1"
minus = "pec"
closed = true
flip = false
