using MoM_AllinOne
using LinearAlgebra
using JLD2

# Set Precision
setPrecision!(Float64)
SimulationParams.SHOWIMAGE = false

# Mesh File (Generated by previous script)
filename = joinpath(@__DIR__, "..", "temp_sphere.nas")
meshUnit = :m

# Frequency
frequency = 300e6 # 300 MHz

# Integral Equation
ieT  = :CFIE

# Basis Functions
sbfT = :RWG
vbfT = :nothing

# Solver
solverT = :gmres
rtol    = 1e-4
restart = 100

# Source
# Incident from -z (theta=pi), propagating in +z
# Polarization along x (alpha=0)
source  = PlaneWave(π, 0.0, 0.0, 1.0)

# Observation Angles
θs_obs_vec = collect(0:0.01:pi)
θs_obs = convert(Vector{Precision.FT}, θs_obs_vec)
ϕs_obs  =   [0.0]

println("Running Legacy MoM_AllinOne Solver (Direct)...")

# --- Code from direct_solver.jl (Modified) ---

# 更新参数
inputParameters(;frequency = frequency, ieT = ieT)
updateVSBFTParams!(;sbfT = sbfT, vbfT = vbfT)

# 网格文件读取
meshData, εᵣs   =  getMeshData(filename; meshUnit=meshUnit);

# 基函数生成
ngeo, nbf, geosInfo, bfsInfo =  getBFsFromMeshData(meshData; sbfT = sbfT, vbfT = vbfT)

# 设置介电参数
setGeosPermittivity!(geosInfo, 2(1-0.0002im))

# 矩阵元计算
println("Calculating Impedance Matrix...")
Zmat = getImpedanceMatrix(geosInfo, nbf)

# 激励向量
println("Calculating Excitation...")
V    =   getExcitationVector(geosInfo, size(Zmat, 1), source);

# 求解
println("Solving...")
# Use LU for direct solver
# ICoeff, ch   =   solve(Zmat, V; solverT = :lu);
ICoeff = Zmat \ V

# Save Matrix and Vector
jldsave(joinpath(@__DIR__, "..", "legacy_matrix.jld2"); Z=Zmat, V=V, I=ICoeff)

using LinearAlgebra
@info norm(Zmat) norm(V)
# RCS
println("Calculating RCS...")
RCSθsϕs, RCSθsϕsdB, RCS, RCSdB = radarCrossSection(θs_obs, ϕs_obs, ICoeff, geosInfo) 

# --- End of direct_solver.jl ---

# Save Results
output_file = joinpath(@__DIR__, "..", "legacy_rcs_reference.txt")
println("Saving RCS to $output_file...")

open(output_file, "w") do io
    println(io, "Theta,RCS_dBsm")
    for i in 1:length(θs_obs)
        # RCS is linear scale (m^2)
        rcs_val = RCS[i]
        rcs_db = 10 * log10(rcs_val)
        println(io, "$(θs_obs[i]),$rcs_db")
    end
end

println("Done.")
