name = "V1_sphere_VEFIE_Mie"
geo = "sphere_r0p15.geo"
mesh_size = 0.04
dim = 3
freq = 6.0e8
ie = "auto"
alpha = 0.5
theta_inc = 1.5707963267948966
phi_inc = 3.141592653589793
pol = [0.0, 0.0, 1.0]
n_theta = 181
phi_cuts = [0.0, 1.5707963267948966]
mie_radius = 0.15

[[region]]
surface = "body"
material = "dielectric:4:0:1"
